services:
  app:
    build:
      context: ./api
    ports:
      - "3333:3333"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    command: sh -c 'ls && npm i && npm run prisma && npm run prisma:migrate && npx prisma db seed && npm run dev'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"